### ISSUE TITLE
[REQ] add tests for plugins

### ISSUE THREAD

**Issue by sozercan** [project-copacetic/copacetic#387]
### What kind of request is this?

Improvement of existing experience

### What is your request or suggestion?

add test for scanner plugin flow

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.

**Comment by anubhav06** [comment]
In order to go install, we will need a release of the scanner-plugin-template, right?
We can also install using something like:
```bash
curl -sfL https://github.com/project-copacetic/scanner-plugin-template/releases/download/v${SCANNER_PLUGIN_TEMPLATE_VERSION}/scanner-plugin-template_${SCANNER_PLUGIN_TEMPLATE_VERSION}_Linux-64bit.tar.gz -o scanner-plugin-template.tar.gz
sudo tar -zxvf scanner-plugin-template.tar.gz -C /usr/local/bin/
rm scanner-plugin-template.tar.gz
```
similar to how [other tools are installed](https://github.com/project-copacetic/copacetic/blob/main/.github/workflows/scripts/download-tooling.sh) in the copa CI, however even that would require a release of the fake-plugin.

**Comment by sozercan** [comment]
@anubhav06 you should be able to `go install github.com/project-copacetic/scanner-plugin-template@latest`, would that work?

**Comment by anubhav06** [comment]
it doesn't, I tried running it locally, but it doesn't do anything. I think it takes into account the "latest" release rather than the latest version

**Comment by anubhav06** [comment]
yes will work. 👍🏻  
sorry I had been looking for the built executable in the wrong path
