### ISSUE TITLE
[QUESTION] Does this support prisma cloud

### ISSUE THREAD

**Issue by smartaquarius10** [project-copacetic/copacetic#552]
### What is your question?

Can we integrate this with twistcli. Many organisations use prisma cloud. 

Any updates on this?

**Comment by sozercan** [comment]
@smartaquarius10 yes, you can extend copa to support any scanner https://project-copacetic.github.io/copacetic/website/scanner-plugins 
please note that copa itself doesn't provide any built-in support for prisma.

we are working on updating packages without scanners reports in #548

**Comment by smartaquarius10** [comment]
@sozercan Sure.. Will definitely try working on it.. Will reach out to you if any help needed as this will be my first time involvement into an opensource community as a contributor.

**Comment by tanulbh** [comment]
@sozercan 

The Twistlock CLI is exclusively available for download from the Prisma Cloud Management Portal, which is only accessible to users with a valid license. I've written the plugin to integrate it with Copacetic, however, I'm uncertain if that's permissible. The crux of the issue is that the JSON report, which my code processes, originates from a CLI tool which is downloaded from a licensed portal.

Although plugin only parses a file, the fact that this file is produced by a licensed application complicates matters. I'm unsure where to find guidance on this issue.


Any suggestion?

**Comment by sozercan** [comment]
Unfortunately, I don't have access to any paid/enterprise scanning solutions, and I can't comment on the licences for those.

In the next release, copa will be able to patch without scanner reports, that might make things easier for you.

**Comment by tanulbh** [comment]
@sozercan oh that’s great. Will try that one. But still, there must be some medium through which tool gets list of vulnerabilities internally. Are we only dependent on trivy then? Or, you are writing some custom code in copacetic to get list of vulnerabilities.

**Comment by sozercan** [comment]
@tanulbh no list of vulnerabilities needed, copa will upgrade all packages if no report and scanner is specified. since this is a superset of vuln packages, vulns should also be resolved.
 
if you want to constraint to vuln packages only, then you can use scanner reports, which is the behavior today.

**Comment by tanulbh** [comment]
@sozercan oh got it. Thank you so much.

A quick question. How/where to start to be a contributor in copacetic project. I am really interested in working on this project

**Comment by tanulbh** [comment]
@sozercan could you please guide me a little on this

**Comment by sozercan** [comment]
@tanulbh we would love you contributing! we have contributing guide here https://project-copacetic.github.io/copacetic/website/contributing doc has the community slack documented if you have any questions

**Comment by tanulbh** [comment]
@sozercan Thanks for sharing. Will check that.
