### ISSUE TITLE
[REQ] modular scanners

### ISSUE THREAD

**Issue by sozercan** [project-copacetic/copacetic#59]
### What kind of request is this?

New feature

### What is your request or suggestion?

It would be good to have scanners to be modular so they don't have to live in the core copacetic repository. The intention is for others to contribute without each scanner being part of the core copa.

perhaps a model like https://github.com/deislabs/ratify/blob/main/pkg/verifier/plugin/skel/skel.go https://github.com/deislabs/ratify/blob/main/plugins/verifier/licensechecker/licensechecker.go (example) which defines inputs and outputs might work

**Comment by salaxander** [comment]
Design doc in progress here: https://docs.google.com/document/d/1AnWQdnujg06GrG7fbioBGwXC1_Bv-BeGqv-5BYPqrKQ/edit

**Comment by sozercan** [comment]
related #32

If we can get SARIF or the scanners (like trivy, grype, etc) to support the required fields, we might be okay to use SARIF directly instead of scanner support

**Comment by anubhav06** [comment]
Has the work on this started? 
Is there any way I can help/contribute to this. Maybe I can add plugin for grype scan results?

**Comment by anubhav06** [comment]
I tried implementing this feature, wherein Trivy remains the default scanner, otherwise we can specify a custom scanner to use with the `--scanner` flag. It's not complete, only in draft stage (no "clean code"), just to get feedback, if I'm approaching it the right way, and if that's what is expected.
I've tried implementing it with Grype custom scanner which I've written
Can I share the draft PR for what I have implemented? (if the work on this has not already started)
