### ISSUE TITLE
[QUESTION] Will Copa have the plan to fix Python and Go Package Security Issues？

### ISSUE THREAD

**Issue by JackTien** [project-copacetic/copacetic#851]
### What is your question?

Will Copa support fixing security vulnerabilities in Python, Go, and other application packages through package manager tools like pip or go get, etc.?

**Comment by sozercan** [comment]
@JackTien please see FAQ https://project-copacetic.github.io/copacetic/website/faq#what-kind-of-vulnerabilities-can-copa-patch

**Comment by JackTien** [comment]
Hi @sozercan , Thanks for the quick reply. I understand and tested for COPA. COPA can fix OS vulns very well. 
However, there still are security issues in applications.(python and go, shown below) 
I just want to know whether COPA will have any plan to support that.

----TRIVY SCAN---
Python (python-pkg)

Total: 4 (UNKNOWN: 0, LOW: 0, MEDIUM: 3, HIGH: 1, CRITICAL: 0)

usr/local/bin/helm (gobinary)

Total: 3 (UNKNOWN: 0, LOW: 0, MEDIUM: 2, HIGH: 1, CRITICAL: 0)

**Comment by sozercan** [comment]
@JackTien answer is no, and yes 😄

Copa is specifically targeted towards packages since it provides a "safer" way to upgrade without breaking compatibility since packages are maintained to ensure the backwards compat doesn't break and any security or other patches can be done. Additionally, copa doesn't know where your code is located nor any compiler flags to build your application. In these aspects, copa will not be able to patch these types of vulnerabilities (such as Go packages) by itself.

However, we are working on a project called https://github.com/Azure/dalec which creates packages and containers from these packages. With Dalec, you'll be able to create packages, and patch with copa. Here's a demo: https://github.com/sozercan/dalec-copa-demo

**Comment by JackTien** [comment]
Hi @sozercan , Thanks for the information, I'll also continue watching the progress of the reproducible build mechanisms.
